"""
AI Provider Request and Response Models.
Defines provider-neutral data transfer models used across the system.
"""

from typing import Any, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field


class UsageMetadata(BaseModel):
    """Token accounting metadata returned by generative AI providers."""

    prompt_tokens: Optional[int] = Field(default=None, description="Number of tokens in the input prompt")
    completion_tokens: Optional[int] = Field(default=None, description="Number of tokens in the generated completion")
    total_tokens: Optional[int] = Field(default=None, description="Total tokens consumed by the interaction")

    model_config = ConfigDict(from_attributes=True)


class ProviderRequest(BaseModel):
    """Standardized input request payload for AI model generation."""

    prompt: str = Field(..., description="User or context prompt string")
    system_prompt: Optional[str] = Field(default=None, description="Optional system-level instruction/persona")
    temperature: Optional[float] = Field(default=None, ge=0.0, le=2.0, description="Sampling temperature")
    max_tokens: Optional[int] = Field(default=None, gt=0, description="Maximum tokens allowed in output")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Safe auxiliary request metadata")

    model_config = ConfigDict(from_attributes=True)


class ProviderResponse(BaseModel):
    """Standardized output response payload from any AI provider."""

    generated_text: str = Field(..., description="Normalized text output generated by the AI model")
    provider: str = Field(..., description="Provider identity (e.g. demo, openai, gemini)")
    model: str = Field(..., description="Model identifier used for generation")
    usage: Optional[UsageMetadata] = Field(default=None, description="Token consumption metrics where available")
    finish_reason: Optional[str] = Field(default=None, description="Completion termination reason (e.g. stop, length)")
    latency_ms: Optional[float] = Field(default=None, description="Total generation duration in milliseconds")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Safe internal metadata (e.g. is_demo flag)")

    model_config = ConfigDict(from_attributes=True)
